packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@journeyapps/wa-sqlite': true
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true

catalog:
  "@journeyapps/wa-sqlite": ^1
  "@prisma/adapter-pg": ^7
  "@prisma/client": ^7
  "@powersync/common": ^1
  "@powersync/drizzle-driver": ^0
  "@powersync/react-native": ^1
  "@powersync/tauri-plugin": ^0
  "@powersync/web": ^1
  "@types/node": ^24.5.2
  argon2: ^0.44
  better-sqlite3: ^12
  dotenv: ^17
  drizzle-kit: ^0.31
  drizzle-orm: ^0.44
  eslint: ^9.39.1
  hono: ^4
  jsonwebtoken: ^9
  pg: ^8
  prisma: ^7
  tsx: ^4
  typescript: ^5
  zod: ^4
